# Generated by Django 5.2.8 on 2026-02-27 09:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IngredientCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Ingredient Categories",
            },
        ),
        migrations.CreateModel(
            name="NutrientCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Nutrient Categories",
                "ordering": ["display_order"],
            },
        ),
        migrations.CreateModel(
            name="Recipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=300)),
                ("description", models.TextField(blank=True)),
                (
                    "serving_size",
                    models.FloatField(
                        default=100,
                        help_text="Serving size amount",
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                (
                    "serving_unit",
                    models.CharField(
                        choices=[
                            ("g", "grams"),
                            ("ml", "milliliters"),
                            ("piece", "piece(s)"),
                        ],
                        default="g",
                        max_length=10,
                    ),
                ),
                (
                    "servings_per_pack",
                    models.FloatField(
                        default=1,
                        help_text="Number of servings per package",
                        validators=[django.core.validators.MinValueValidator(0.1)],
                    ),
                ),
                ("brand_name", models.CharField(blank=True, max_length=200)),
                ("manufacturer", models.CharField(blank=True, max_length=300)),
                (
                    "fssai_license",
                    models.CharField(
                        blank=True, help_text="FSSAI license number", max_length=20
                    ),
                ),
                (
                    "allergen_info",
                    models.TextField(blank=True, help_text="Allergen declarations"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, unique=True)),
                (
                    "aliases",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated alternative names for fuzzy matching",
                    ),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ingredients",
                        to="labels.ingredientcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Nutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "unit",
                    models.CharField(help_text="e.g., g, mg, µg, kcal", max_length=20),
                ),
                (
                    "daily_value",
                    models.FloatField(
                        blank=True,
                        help_text="FSSAI recommended daily value for %DV calculation",
                        null=True,
                    ),
                ),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "is_mandatory",
                    models.BooleanField(
                        default=False,
                        help_text="Whether this nutrient is mandatory on FSSAI labels",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrients",
                        to="labels.nutrientcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["category__display_order", "display_order"],
            },
        ),
        migrations.CreateModel(
            name="GeneratedLabel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "format",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("png", "PNG"), ("html", "HTML")],
                        default="pdf",
                        max_length=10,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=500)),
                (
                    "nutrition_data",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Snapshot of nutrition data at generation time",
                    ),
                ),
                ("is_fssai_compliant", models.BooleanField(default=False)),
                ("compliance_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="labels.recipe",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IngredientNutrient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value_per_100g",
                    models.FloatField(
                        help_text="Amount per 100g of ingredient",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nutrients",
                        to="labels.ingredient",
                    ),
                ),
                (
                    "nutrient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredient_values",
                        to="labels.nutrient",
                    ),
                ),
            ],
            options={
                "unique_together": {("ingredient", "nutrient")},
            },
        ),
        migrations.CreateModel(
            name="RecipeIngredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weight_grams",
                    models.FloatField(
                        help_text="Weight in grams",
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "ingredient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipe_uses",
                        to="labels.ingredient",
                    ),
                ),
                (
                    "recipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredients",
                        to="labels.recipe",
                    ),
                ),
            ],
            options={
                "unique_together": {("recipe", "ingredient")},
            },
        ),
    ]
