# Generated by Django 5.2.8 on 2026-02-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0002_alter_generatedlabel_format'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generatedlabel',
            name='format',
            field=models.CharField(choices=[('pdf', 'PDF'), ('html', 'HTML'), ('json', 'JSON'), ('csv', 'CSV')], default='pdf', max_length=10),
        ),
    ]
