# Generated by Django 5.2.8 on 2026-02-27 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_add_user_to_recipe'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDefaults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_brand_name', models.CharField(blank=True, max_length=200)),
                ('default_manufacturer', models.CharField(blank=True, max_length=300)),
                ('default_fssai_license', models.CharField(blank=True, max_length=20)),
                ('default_serving_size', models.FloatField(default=100)),
                ('default_serving_unit', models.CharField(default='g', max_length=10)),
                ('default_servings_per_pack', models.FloatField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='defaults', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Defaults',
            },
        ),
        migrations.CreateModel(
            name='RecipeVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField(default=1)),
                ('snapshot', models.JSONField(default=dict, help_text='Full recipe + nutrition + compliance snapshot')),
                ('is_compliant', models.BooleanField(default=False)),
                ('change_summary', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='labels.recipe')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('recipe', 'version_number')},
            },
        ),
    ]
